export const downloadJSON = (result) => {
  const blob = new Blob([JSON.stringify(result, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `deadline-rescue-report-${result.analysis_id || "demo"}.json`;
  a.click();
};

export const printPDF = () => {
  window.print();
};

export const downloadICS = (events = []) => {
  if (!events.length) {
    alert("No calendar events found.");
    return;
  }

  const formatDate = (dateString) => {
    return dateString.replace(/[-:]/g, "").split(".")[0];
  };

  const icsEvents = events
    .map(
      (event) => `
BEGIN:VEVENT
SUMMARY:${event.title}
DTSTART:${formatDate(event.start_time)}
DTEND:${formatDate(event.end_time)}
DESCRIPTION:Generated by Deadline Rescue AI
END:VEVENT`
    )
    .join("");

  const icsContent = `
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Deadline Rescue AI//EN
${icsEvents}
END:VCALENDAR`;

  const blob = new Blob([icsContent], { type: "text/calendar" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "deadline-rescue-calendar.ics";
  a.click();
};

export const speakText = (text) => {
  if (!window.speechSynthesis) {
    alert("Speech output not supported.");
    return;
  }

  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.rate = 1;
  utterance.pitch = 1;
  window.speechSynthesis.speak(utterance);
};

export const formatDateTime = (value) => {
  if (!value) return "Not scheduled";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return date.toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
};

export const sendScheduleMail = (dayWisePlan = []) => {
  if (!dayWisePlan.length) {
    alert("No day-wise schedule found.");
    return;
  }

  const body = dayWisePlan
    .map((day) => {
      const blocks = day.blocks
        ?.map(
          (b) =>
            `${b.start_time} - ${b.end_time}: ${b.task_name}\n${b.expected_output}`
        )
        .join("\n\n");

      return `${day.day_label} (${day.date})\n${blocks}`;
    })
    .join("\n\n--------------------\n\n");

  const mailto = `mailto:?subject=My Deadline Rescue Schedule&body=${encodeURIComponent(
    body
  )}`;

  window.location.href = mailto;
};